### ISSUE TITLE
Support for Twitter API 1.1

### ISSUE THREAD

**Issue by alfjjacob** [share-extras/twitter-dashlets#1]
Hello,

Is there any plan to support the new Twitter 1.1 api? Twitter Feed dashlet no longer works with the new API which requires authentication. 

Any ideas/suggestions to modify the existing code to support it? 

Thanks

**Comment by wabson** [comment]
The 1.1 API is now used instead of 1.0 in the latest code. Due to the authentication policy change, all dashlets now require the user to connect to Twitter before content can be shown.

I also noticed that the rate limits seem a little lower than they were for the 1.0. I hit these limits in my testing, but perhaps they will not be an issue during normal use. Please raise a new issue if you have problems with this, or any other issue.
